# Generated by Django 4.0.4 on 2022-04-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_profile_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_Img',
            field=models.ImageField(default='Image is not here', upload_to='images/'),
        ),
    ]
